[package]
name = "pxlclnt"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version= "1.27.0", features = ["full"] }
clap = "4.2.4"
clap_derive = "4.2.0"
nom = "7.1.3"